// Re-exportar hooks
export { useAuth, AuthProvider } from './useAuth'
export { useProjects } from './useProjects' // Usar versión real de Supabase
export { useFloors } from './useFloors'
export { useTowers } from './useTowers'
export { useApartments } from './useApartments'
export { useTasks } from './useTasks'
export { useTasksV2 } from './useTasks_v2'
export { useDashboard } from './useDashboard'
export { useReports } from './useReports'
export { useMaterials } from './useMaterials'
export { useWarehouses } from './useWarehouses'
export { useMaterialMovements } from './useMaterialMovements'
export { useAttendance } from './useAttendance'
export { useAttendanceStats } from './useAttendanceStats'
export { useNotifications } from './useNotifications'
export { useTaskTemplates } from './useTaskTemplates'
